<img src=images/gdd-logo.png width=300px align=right> 

# Aggregation in Pandas

This section covers all about aggregating with `df.groupby()`, including:

* [Grouped aggregation in pandas](#grouped-agg)
* [Single aggregations with `df.groupby()`](#groupby)
* [Multiple aggregations with `.agg()`](#mult-aggs)
* [<mark>Exercise: Using aggregations</mark>](#ex-aggs)

Let's import pandas and load the data again, since this is a new notebook.

In [47]:
import pandas as pd

chickweight = (
    pd.read_csv('data/chickweight.csv')
    .rename(str.lower, axis='columns')
)

To get statistics for the data you can use methods like:

* `df.describe()`: gives a selection of statistics for each numeric field
* `df.mean()`: calculates the mean of each column or row
* `df.max()`: calculates the max of each column or row
* `df.min()`: calculates the min of each column or row

In [2]:
chickweight.describe()

           rownum      weight        time       chick        diet
count  578.000000  578.000000  578.000000  578.000000  578.000000
mean   289.500000  121.818339   10.717993   25.750865    2.235294
std    166.998503   71.071960    6.758400   14.568795    1.162678
min      1.000000   35.000000    0.000000    1.000000    1.000000
25%    145.250000   63.000000    4.000000   13.000000    1.000000
50%    289.500000  103.000000   10.000000   26.000000    2.000000
75%    433.750000  163.750000   16.000000   38.000000    3.000000
max    578.000000  373.000000   21.000000   50.000000    4.000000

In [3]:
chickweight.mean()

rownum    289.500000
weight    121.818339
time       10.717993
chick      25.750865
diet        2.235294
dtype: float64

<a id = 'grouped-agg'></a>
## Grouped Aggregation in Pandas

However, what if you want data about specific groups of the dataset, e.g. the mean weight for diet 2. In that case you need to ***aggregate*** the data.

Aggregation is the act of splitting up the original dataset to calculate statistics on sub-dataframes.

<img src="images/03_Aggregations/split-groupby-combine.png" width="440" height="440" align="center"/>

There are a few ways to do this in pandas:. 

<a id = 'groupby'></a>
## Single aggregations

To get the overall mean weight you can use:

In [ ]:
(
    chickweight
    ['weight']
    .mean()
)

But what if you want to see what the mean weight is depending on the diet the chicken was on?

Then you first need to perform a `.groupby()` in order to split the data into those different diets.

In [6]:
(
    chickweight
    .groupby('diet')
    ['weight']
    .mean()
)

diet
1    102.645455
2    122.616667
3    142.950000
4    135.262712
Name: weight, dtype: float64

### <mark>Practice: Try out groupby</mark>

1. Find the minumum `weight` of the chickens at each `time` period.

In [9]:
chickweight.groupby('time')['weight'].min()

time
0     39
2     35
4     48
6     51
8     57
10    51
12    54
14    68
16    71
18    72
20    76
21    74
Name: weight, dtype: int64

There are lots of statistics that can be applied to numerical columns, like:
* `.mean()`
* `.sum()`
* `.min()` and `.max()`
* `.first()`
* `.var()`
* `.size()`
* `.count()`

2. Try them out. What does each one do?</mark>

In [ ]:
# chickweight.groupby('time')['weight'].mean()
# chickweight.groupby('time')['weight'].sum()
# chickweight.groupby('time')['weight'].min()
# chickweight.groupby('time')['weight'].max()
# chickweight.groupby('time')['weight'].first()# first non-null entry
# chickweight.groupby('time')['weight'].var() #variance
# chickweight.groupby('time')['weight'].size() #total rows
# chickweight.groupby('time')['weight'].count() #non null values

# chickweight.groupby('time')['weight'].median() # median
# chickweight.groupby('time')['weight'].std() # standard deviation

time
0     50
2     50
4     49
6     49
8     49
10    49
12    49
14    48
16    47
18    47
20    46
21    45
Name: weight, dtype: int64

In [16]:
# %load answers/03_Aggregations/practice-aggs.py

(
    chickweight
    .groupby("time")
    ["weight"]
    .min()
)

time
0     39
2     35
4     48
6     51
8     57
10    51
12    54
14    68
16    71
18    72
20    76
21    74
Name: weight, dtype: int64

<details>
    
  <summary><span style="color:blue">Show answer</span></summary>
  
* `.mean()`: Return the mean of the values 
* `.sum()`: Return the sum of the values 
* `.min()` and `.max()`: Return the minimum or maximum of the values 
* `.first()`: Return the first non-null entry of each column
* `.var()`: Return the variance of each column
* `.size()`: Return the number of rows 
* `.count()`: Return the count of non-null entries of each column

</details>

<mark>**Question:** What happens to the index when you use groupby?</mark>

Answer: is redefined

<details>
    
  <summary><span style="color:blue">Show answer</span></summary>
  
Whatever column(s) you group on will become the new index. 

</details>

You can even perform aggregations when the data is grouped by **multiple** columns:

In [17]:
(
    chickweight
    .groupby(['diet', 'time'])
    .mean()
)

               rownum      weight      chick
diet time
1    0     111.400000   41.400000  10.500000
     2     112.400000   47.250000  10.500000
     4     109.000000   56.473684  10.105263
     6     110.000000   66.789474  10.105263
     8     111.000000   79.684211  10.105263
     10    112.000000   93.052632  10.105263
     12    113.000000  108.526316  10.105263
     14    110.166667  123.388889   9.777778
     16    107.352941  144.647059   9.470588
     18    108.352941  158.941176   9.470588
     20    109.352941  170.411765   9.470588
     21    111.250000  177.750000   9.562500
2    0     275.000000   40.700000  25.500000
     2     276.000000   49.400000  25.500000
     4     277.000000   59.800000  25.500000
     6     278.000000   75.400000  25.500000
     8     279.000000   91.700000  25.500000
     10    280.000000  108.500000  25.500000
     12    281.000000  131.300000  25.500000
     14    282.000000  141.900000  25.500000
     16    283.000000  164.700000  25.500000
     18    284.000000  187.700000  25.500000
     20    285.000000  205.600000  25.500000
     21    286.000000  214.700000  25.500000
3    0     395.000000   40.800000  35.500000
     2     396.000000   50.400000  35.500000
     4     397.000000   62.200000  35.500000
     6     398.000000   77.900000  35.500000
     8     399.000000   98.400000  35.500000
     10    400.000000  117.100000  35.500000
     12    401.000000  144.400000  35.500000
     14    402.000000  164.500000  35.500000
     16    403.000000  197.400000  35.500000
     18    404.000000  233.100000  35.500000
     20    405.000000  258.900000  35.500000
     21    406.000000  270.300000  35.500000
4    0     513.800000   41.000000  45.500000
     2     514.800000   51.800000  45.500000
     4     515.800000   64.500000  45.500000
     6     516.800000   83.900000  45.500000
     8     517.800000  105.600000  45.500000
     10    518.800000  126.000000  45.500000
     12    519.800000  151.400000  45.500000
     14    520.800000  161.800000  45.500000
     16    521.800000  182.000000  45.500000
     18    522.800000  202.900000  45.500000
     20    525.666667  233.888889  45.666667
     21    526.666667  238.555556  45.666667

If grouping by more than one column, the indices will be nested in a _multiindex_, with the order of the list items determining the hierarchy (e.g. `['diet', 'time']` will first group by diet and then within each diet by time).

To take those columns out of the index we can use the `.reset_index()` method.

<mark>**Question**: Why does the below code *not work* when you comment out `.reset_index()`?</mark>

In [20]:
# because in the .loc it is creating a list of booleans that refers back to the index

(
    chickweight
    .groupby(['time', 'diet'])
    .mean()
    .reset_index()
    .loc[lambda df: df['time'] == 10]
)

    time  diet  rownum      weight      chick
20    10     1   112.0   93.052632  10.105263
21    10     2   280.0  108.500000  25.500000
22    10     3   400.0  117.100000  35.500000
23    10     4   518.8  126.000000  45.500000

<details>
    
  <summary><span style="color:blue">Show answer</span></summary>
  
  Because we are using a filter on the column `time` and when we perform a `.groupby()` on `time` and `diet` these columns become the index of the resulting dataframe. Therefore we cannot filter as we would if they were *normal* columns. 
    
   When you use `.reset_index()` it resets the time and diet as columns and therefore they can be used in the filter.
    
    
   Sometimes this is fine, but sometime you might want to undo this operation by resetting the index. You can use `.reset_index()` at the end to do this.

   The index of a dataframe typically has different behavior than a column.

</details>

<a id = 'mult-aggs'></a>
## Multiple aggregations with `.agg()`

You can get the results for more than one aggregation by using a keyword for the name of the **output column** and a tuple to specificy the **old columns** and the **aggregator** to use. 

```python
df
.groupby('grouping_col')
.agg(output_col = ('old_col', 'aggregator'))
```

**Example**: Find the size of `chick` and mean value for `weight` when grouped by `time`

In [ ]:
(
    chickweight
    .groupby('time')
    .agg(num_chickens = ('chick', 'size'), 
         weight_mean = ('weight', 'mean'),
        )
)

Note: this way of aggregating became available in `pandas > 0.25`. To check your pandas version you can run the following cell:

In [21]:
pd.__version__

'2.2.3'

<a id = 'ex-aggs'></a>
### <mark>Exercise: Using aggregations</mark>

Determine the following aggregate information **per time period**:

- maximum chick id (use the chick column)
- median weight
- std (standard deviation) of weight

- any extras of your choice

**Bonus**: Once you have performed the `.groupby()`, filter the data to only show when the median weight exceeds `150g`.

In [33]:
(
    chickweight
    .groupby(['time'])
    .agg(
        num_chickens = ('chick','max'),
        med_weight = ('weight','median'),
        weight_std = ('weight','std'),
        diet_count = ('diet','count'),
    )
)

      num_chickens  med_weight  weight_std  diet_count
time
0               50        41.0    1.132272          50
2               50        49.0    3.688316          50
4               50        61.0    4.495179          49
6               50        74.0    9.012038          49
8               50        90.0   16.239780          49
10              50       109.0   23.987277          49
12              50       134.0   34.119600          49
14              50       146.5   38.300412          48
16              50       169.0   46.904079          47
18              50       187.0   57.394757          47
20              50       204.0   66.511708          46
21              50       205.0   71.510273          45

In [57]:
############ testing for partition by
chickweight.assign(
    weight_lag = lambda df: df.groupby('chick')['weight'].shift(1),
    weight_diff = lambda df: df['weight'] - df['weight_lag']
).head()

   rownum  weight  time  chick  diet  weight_lag  weight_diff
0       1      42     0      1     1         NaN          NaN
1       2      51     2      1     1        42.0          9.0
2       3      59     4      1     1        51.0          8.0
3       4      64     6      1     1        59.0          5.0
4       5      76     8      1     1        64.0         12.0

In [ ]:
# %load answers/03_Aggregations/ex-aggs.py

# Conclusion

You have now seen how to do a single aggregation, for example:

```python
(
    df
    .groupby('column')
    .mean()
)
```

And also that you can do multiple aggregations, with control over the output column name, for example:

```python
(
    df
    .groupby('column')
    .agg(min_col = ('old_col', 'min'),
         max_col = ('col_col', 'max')
        )
)
```

An important thing to note is that the pandas GroupBy object is **not a DataFrame until you perform some kind of aggregation function**. 

Once it is a dataframe, you can perform any DataFrame method, for example performing `.loc[]`.